import { Providers } from "@/src/context/providers";
import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: `${process.env.NEXT_PUBLIC_SITE_NAME} POS System`,
  description: "Generated by create next app",
  icons: {
    icon: "/chica_icon.svg",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  viewportFit:'cover',
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 使用 h-full (100%) 確保根節點撐滿
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <Providers>{children}</Providers>
        <Toaster position={"bottom-right"} />
      </body>
    </html>
  );
}
